### ISSUE TITLE
add start button

### ISSUE THREAD

**Issue by tw1003** [tw1003/KenkouLauncher#2]
add a button to the main formular that invokes the starting process for another tool

**Comment by steffi0202** [comment]
how i get access to the other tool? http link or jar file on my local system?

**Comment by tw1003** [comment]
the other tool will be a jar file contained within the same folder as the
launcher tool.
The updates will be stored in amazon s3 storage, which will contain all the
necessary update information and files.

2015-09-07 18:54 GMT+02:00 steffi0202 <notifications@github.com>:

**Comment by tw1003** [comment]
I pushed some changes to the repository and added a new issue ( add image
to repository <https://github.com/tw1003/KenkouLauncher/issues/5> ) ,
please have a look at this, i added a comment in MainFormular.java as well.
The application compiles and builds quite nicely, but seems to hang on
start. Doesn't matter whether i start the application from ide or via
commandline.
So i was not able to take a look at the formular itself so far.

2015-09-08 9:13 GMT+02:00 Tobias Wormstaedt <t.wormstaedt@kenkou.de>:

**Comment by steffi0202** [comment]
included
