### ISSUE TITLE
add image to repository

### ISSUE THREAD

**Issue by tw1003** [tw1003/KenkouLauncher#5]
Add the image file referenced in MainFormular.java to the repository and correct the path.

**Comment by steffi0202** [comment]
what is the image and how is the correct path?

**Comment by tw1003** [comment]
You added an image/icon to one of the labels of the old MainFormular class.
I don't know if this is also true for the new MainFormular class.
Please verify if there is any image included, if not just close this issue
as irrelevant.

2015-09-08 13:50 GMT+02:00 steffi0202 <notifications@github.com>:
